Fix ``fatal error: wlr/render/allocator.h: No such file or directory` and other wlroots compilation errors (#11)
wlroots recently moved to freedesktop's gitlab. Fix that and make a note on README.